#FROM opensuse/leap:15.3 as builder-api
FROM targoman/api-devel:1 as builder-api
LABEL maintainer="S.Mehran M.Ziabary <ziabary@targoman.com>"

WORKDIR /opt

#RUN zypper ar --no-gpgcheck https://download.opensuse.org/repositories/home:/targoman/15.3/home:targoman.repo
#RUN zypper ref
#RUN zypper --non-interactive in \
#      wget \
#      vim \
#      git \
#      which \
#      unzip \
#      zlib-devel \
#      hiredis-devel \
#      libcurl-devel \
#      libQt5Sql-devel \
#      libQt5Sql5-mysql \
#      libQt5Test-devel  \
#      libQt5Network-devel \
#      libQt5Concurrent-devel \
#      libqt5-qtwebsockets-devel \
#      libboost_thread1_75_0-devel \
#      libboost_system1_75_0-devel \
#      gtest \
#      protobuf-devel \
#      libicu-devel \
#      libopenssl-devel \
#      libphonenumber-devel

#aws-sdk-cpp-s3-devel

#RUN git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp && \
#    mkdir aws-build.s3 && \
#    cd aws-build.s3 && \
#    cmake ../aws-sdk-cpp -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_PREFIX_PATH=/usr -DBUILD_ONLY="s3" && \
#    make -j install && \
#    cd ..

COPY . .

ARG TAG
RUN echo $TAG
RUN qmake-qt5 QJsonRPC=0 CONFIG+=debug GIT_VERSION=$TAG NOTEST=1 && make -j 4                                                                                                                                                                                                                                                           && rm -rf out/build out/submodules/ out/unitTest out/test

#FROM opensuse/leap:15.3 as builder-mt
FROM targoman/api-devel:1 as builder-mt
COPY ./MT/ .
RUN qmake-qt5 QJsonRPC=0 CONFIG+=debug GIT_VERSION=$TAG NOTEST=1 && make -j 4 && rm -rf out/build out/submodules/ out/unitTest out/test

#FROM opensuse/leap:15.3
#FROM targoman/api-devel:1
FROM targoman/api-devel:1-build

#RUN zypper ar --no-gpgcheck https://download.opensuse.org/repositories/home:/targoman/15.3/home:targoman.repo
#RUN zypper ref && \
#    zypper --non-interactive in \
#      libhiredis0_13 \
#      libcurl4 \
#      libQt5Sql5-mysql \
#      libQt5Network5 \
#      libQt5Concurrent5 \
#      libQt5WebSockets5 \
#      libboost_thread1_75_0 \
#      libboost_system1_75_0 \
#      libboost_date_time1_75_0 \
#      libprotobuf20 \
#      libicu \
#      zlib \
#      openssl \
#      libphonenumber8 \
#    && mkdir -p /targoman/bin

#aws-sdk-cpp-s3-libs

RUN mkdir -p /targoman/bin

WORKDIR /targoman
#COPY --from=builder-api /usr/lib64/libaws-cpp-sdk-s3.so /usr/lib64/libaws-cpp-sdk-s3.so
#COPY --from=builder-api /usr/lib64/libaws-cpp-sdk-core.so /usr/lib64/libaws-cpp-sdk-core.so
COPY --from=builder-api /opt/out .
COPY --from=builder-mt /opt/out .
COPY conf conf
COPY Docker/run-targoman-dev.sh .
COPY Docker/migrate-dev.sh .
COPY migrations migrations
COPY SwaggerUI SwaggerUI

ENTRYPOINT [ "/targoman/run-targoman-dev.sh" ]
