name: CI
on:
  pull_request:
    branches:
      - "dev"
  workflow_dispatch:
env:
  PROJECT_NAME: api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: echo "TAG=${{ github.head_ref }}" >> $GITHUB_ENV
      - name: Set the TAG value
        id: build-tag
        run: echo "::set-output name=TAG::$TAG"
      - run: echo "$TAG has been pushed"
      - name: build
        run: mkdir conf/tmp && cp -rL conf/TextProcessor conf/tmp && rm -f conf/TextProcessor && mv conf/tmp/* conf/ && rmdir conf/tmp
      - run: docker build -f Docker/Dockerfile.prod . -t ${{ env.PROJECT_NAME }}:$TAG
      - run: docker save --output="${{ env.PROJECT_NAME }}-$TAG.tar" ${{ env.PROJECT_NAME }}:$TAG
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME }}-docker-image-${{ steps.build-tag.outputs.TAG }}
          path: ${{ env.PROJECT_NAME }}-${{ env.TAG }}.tar

  